### PR TITLE
Update to 0.12.0-dev.2341+92211135f

### PR DESCRIPTION
**Pull request by Cloudef**
Not compatible with 0.11, you might want to hold on this until 0.12 release perhaps.

### CODE REVIEW

**Comment by rsepassi** [comment]
Thanks for doing this. How about pushing to a new branch, "zigmaster"? We can update the main branch README to point to it.

**Comment by Cloudef** [comment]
I think you have to create the zigmaster branch and then the base branch can be changed for this PR.

**Comment by rsepassi** [comment]
Got it, done.

**Comment by Cloudef** [comment]
Thanks changed branch

**Comment by Cloudef** [comment]
I'll update the CI .yml on this branch to fetch the tested zig version

**Comment by rsepassi** [comment]
Thanks!

**Pull request merged**
